name: Deploy Kubernetes

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar código
      uses: actions/checkout@v2

    - name: Configurar JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'

    - name: Compilar com Maven
      run: mvn clean package

    - name: Construir imagem Docker
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/carros:latest .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKER_USERNAME }}/carros:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Baixar código
      uses: actions/checkout@v2

    - name: Configurar kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy para Kubernetes
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      run: |
        echo "${KUBE_CONFIG_DATA}" | base64 --decode > $HOME/.kube/config
        kubectl apply -f k8s/deployment.yaml
